# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f1f5cbce556a4fe7636d339ac59271e2e0c70a059c29c7d3eb6fe73d9d376250d9b9f14d6eabe5d406be3d449e2e33afc8ae50ed4d4e49234189921d8d8dd27

test:
  secret_key_base: b8a47b7ada306f233a26a8624934aecf0696e9e6ae3b05e7306977a3f7033936385bb3b9d43056a0e4200c95b8184b7d0815cf3be1a187617ff2a08e9f0196ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
